/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-radar
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_RADAR_API_H
#define INCLUDED_RADAR_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_radar_EXPORTS
#define RADAR_API __GR_ATTR_EXPORT
#else
#define RADAR_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_RADAR_API_H */
